### PR TITLE
Set sizes metadata to empty array if doesn't exist.

### LINKED ISSUE #60: Error thrown when exif data could not be read for an image
This line throws an exception when the exif data could not be read for an image:
https://github.com/wp-cli/media-command/blob/master/src/Media_Command.php#L719

image

We should probably be resilient to this.

### PR DESCRIPTION
**Pull request by gitlost**
Closes #60 

In `needs_regeneration()`:

-  skips if no image editor available for an image (previously only skipped if PDF) and warns (unless it's a PDF).
- sets the sizes metadata for an image to an empty array if it doesn't exist before checking it.

Reproduces the issue by uploading a BMP with Imagick disabled so no sizes metadata generated.

Also adds attachment ID to some warnings for better feedback, separates out warnings from progress log on metadata error, and adjusts tests.

### CODE REVIEW

File: src/Media_Command.php [hunk 1]
```diff
@@ -693,6 +698,11 @@ private function needs_regeneration( $att_id, $fullsizepath, $is_pdf, $image_siz
 			$metadata['sizes'] = array( $image_size => $metadata['sizes'][ $image_size ] );
 		}
 
+		// In certain situations, eg if file uploaded when applicable image editor such as Imagick unavailable, the sizes metadata may not exist.
+		if ( ! isset( $metadata['sizes'] ) || ! is_array( $metadata['sizes'] ) ) {
+			$metadata['sizes'] = array();
+		}
+
 		if ( $this->image_sizes_differ( $image_sizes, $metadata['sizes'] ) ) {
```
Comment (schlessera) [inline src/Media_Command.php]: Do you think the above logical construction (the check to make sure `$metadata['sizes']` is an array) is useful for documentation purposes?

Otherwise, the code would be cleaner with a simple cast to array in the line where it is used...
```
if ( $this->image_sizes_differ( $image_sizes, (array) $metadata['sizes'] ) ) {
```

**Comment by schlessera** [comment]
Nice, a creative way to force the problem in tests, @gitlost !
